model:
  filters: 8
  kernel: 3
  k_pool: 2
  pool: "max"
  n_cov: 4
  n_dcov: 4
  act: "swish"
  img_size: 256
hyper:
  batch_size: 16
  mode: "3d"
  masking: "../processed_data/PR/Mask/mask_probe_256.npy"
  probe: "../processed_data/PR/Mask/probe_function_256_center.npy"
  probe_mode: "multi_c"
  n_refine: 5
  sample: True
  dist: True
  lr: 0.001
  probe_norm: 3e6
  save_path: "trained_models/AuNP_exp_1s_256_simu_d"
  train_data: "../processed_data/PR/AuNP_realsimu_1s_256_1k/frameimg_exposure_1s_1k_simu.npz"
