model:
  filters: 8
  kernel: 3
  k_pool: 2
  pool: "max"
  n_cov: 4
  n_dcov: 4
  act: "swish"
  img_size: 256
hyper:
  batch_size: 8
  mode: "3d"
  masking: "../../processed_data/PR/Mask/mask_probe_256_circle.npy"
  # masking: ""
  probe: "../../processed_data/PR/Mask/wave_shifted_probe_256_circle.npy"
  probe_mode: "single_c"
  n_refine: 5
  n_time: 5
  sample: "simu"
  dist: True
  lr: 0.001
  probe_norm: 0.1
  save_path: "trained_models/AuNP_simuc_100ms"
  train_data: "../../processed_data/PR/AuNP_simuc_100ms_256_1k/frameimg_exposure_100ms_1k_simu.npz"
