model:
  filters: 8
  kernel: 3
  k_pool: 2
  pool: "max"
  n_cov: 4
  n_dcov: 4
  act: "swish"
  img_size: 256
hyper:
  batch_size: 8
  mode: "3d"
  masking: "../../processed_data/PR/Mask/mask_probe_256.npy"
  probe: "../../processed_data/PR/Mask/probe_function_256_center.npy"
  probe_mode: "multi_c"
  n_refine: 5
  n_time: 5
  sample: "aunp"
  dist: True
  lr: 0.001
  probe_norm: 0.1
  save_path: "trained_models/AuNP_exp_100ms_sum"
  train_data: "../../processed_data/PR/AuNp_expdata/frameimg_exposure_100ms.npz"
