model:
  filters: 8
  kernel: 3
  k_pool: 2
  pool: "max"
  n_cov: 4
  n_dcov: 4
  act: "swish"
  img_size: 384
hyper:
  batch_size: 4
  loss: 2.0
  masking: "../../processed_data/PR/Probe/mask_probe_384_AuNP.npy"
  probe: "../../processed_data/PR/Probe/probe_function_384_AuNP.npy"
  probe_mode: "multi_c"
  n_refine: 5
  n_time: 5
  sample: "simu"
  dist: False
  lr: 0.001
  probe_norm: 0.1
  save_path: "trained_models/public/AuNP_simu_100ms"
  train_data: "../../processed_data/PR/AuNP_realsimu_100ms_384_1k_360nm/frameimg_exposure_100ms_1k_simu.npz"
