model:
  filters: 8
  kernel: 3
  k_pool: 2
  pool: "max"
  n_cov: 4
  n_dcov: 4
  act: "swish"
  img_size: 256
hyper:
  batch_size: 2
  mode: "3d"
  masking: ""
  mask_diff: ""
  probe: "../processed_data/PR/Mask/probe_function_236_dynamic.npy"
  probe_mode: "single_c"
  probe_norm: 1.0
  n_refine: 5
  n_time: 5
  sample: False
  dist: False
  lr: 0.001
  decay: 0.95
  save_path: "trained_models/model_dynamic_data"
  train_data: "../processed_data/PR/Dynamic_data/frame_exposure_10ms_1k.npz"
