model:
  filters: 8
  kernel: 3
  k_pool: 2
  pool: "max"
  n_cov: 4
  n_dcov: 4
  act: "swish"
  img_size: 384
hyper:
  batch_size: 4
  loss: 3.0
  masking: "../../processed_data/PR/Probe/mask_probe_378.npy"
  probe: "../../processed_data/PR/Probe/probe_function_378.npy"
  probe_mode: "multi_c"
  n_refine: 5
  n_time: 5
  sample: "chart"
  dist: True
  lr: 0.001
  probe_norm: 0.00727175
  save_path: "trained_models/public/Moving_chart_15s_7ms"
  train_data: "../../processed_data/PR/Moving_chart/dataset2_15s_25fr_7ms.npz"
